---
APP_CONFIG:
  PREFIX: '/api/1'
  SECRET_KEY: 'a very very secret key preferably through an env variable'  # e.g. like this !ENV ${NAME_OF_VAR}
  SQLALCHEMY_COMMIT_ON_TEARDOWN: True
  UPLOAD_FOLDER: !ENV '${BASKERVILLE_DASH_ROOT}/backend/static/uploads'
  JWT_SECRET_KEY: sosecret
  JWT_DEFAULT_REALM: 'Login Required'
  JWT_AUTH_HEADER_PREFIX: 'Bearer'
  SECURITY_PASSWORD_SALT: 'salt'
  FLASK_DEBUG: True
  ADMIN_EMAIL: 'admin@email'
  ADMIN_PASS: !ENV '${ADMIN_PASS}'
  PIPELINE: 'irawlog'
  BASKERVILLE_CONF: !ENV '${BASKERVILLE_ROOT}/conf/baskerville.yaml'
  KAFKA_TOPICS:
    - 'test.feedback'
    - 'test.registration'